/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteRouteImport } from './routes/_project/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as RReportIdRouteImport } from './routes/r/$reportId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as ProjectPProjectIdRouteRouteImport } from './routes/_project/p/$projectId/route'
import { Route as ProjectPProjectIdIndexRouteImport } from './routes/_project/p/$projectId/index'
import { Route as ApiGscOauthCallbackRouteImport } from './routes/api/gsc/oauth/callback'
import { Route as ApiGa4OauthCallbackRouteImport } from './routes/api/ga4/oauth/callback'
import { Route as ProjectPProjectIdSettingsRouteImport } from './routes/_project/p/$projectId/settings'
import { Route as ProjectPProjectIdSearchPerformanceRouteImport } from './routes/_project/p/$projectId/search-performance'
import { Route as ProjectPProjectIdSavedRouteImport } from './routes/_project/p/$projectId/saved'
import { Route as ProjectPProjectIdRankingsRouteImport } from './routes/_project/p/$projectId/rankings'
import { Route as ProjectPProjectIdOpportunitiesRouteImport } from './routes/_project/p/$projectId/opportunities'
import { Route as ProjectPProjectIdContextRouteImport } from './routes/_project/p/$projectId/context'
import { Route as ProjectPProjectIdAuditRouteImport } from './routes/_project/p/$projectId/audit'
import { Route as ProjectPProjectIdAnalyticsRouteImport } from './routes/_project/p/$projectId/analytics'
import { Route as ProjectPProjectIdSettingsIndexRouteImport } from './routes/_project/p/$projectId/settings/index'
import { Route as ProjectPProjectIdReportsIndexRouteImport } from './routes/_project/p/$projectId/reports/index'
import { Route as ProjectPProjectIdAuditIndexRouteImport } from './routes/_project/p/$projectId/audit/index'
import { Route as ProjectPProjectIdSettingsIntegrationsRouteImport } from './routes/_project/p/$projectId/settings/integrations'
import { Route as ProjectPProjectIdSettingsContextRouteImport } from './routes/_project/p/$projectId/settings/context'
import { Route as ProjectPProjectIdReportsTemplatesRouteImport } from './routes/_project/p/$projectId/reports/templates'
import { Route as ProjectPProjectIdReportsReportIdRouteImport } from './routes/_project/p/$projectId/reports/$reportId'
import { Route as ProjectPProjectIdAuditIssuesResultIdRouteImport } from './routes/_project/p/$projectId/audit/issues/$resultId'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const RReportIdRoute = RReportIdRouteImport.update({
  id: '/r/$reportId',
  path: '/r/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ProjectPProjectIdRouteRoute = ProjectPProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectPProjectIdIndexRoute = ProjectPProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ApiGscOauthCallbackRoute = ApiGscOauthCallbackRouteImport.update({
  id: '/api/gsc/oauth/callback',
  path: '/api/gsc/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGa4OauthCallbackRoute = ApiGa4OauthCallbackRouteImport.update({
  id: '/api/ga4/oauth/callback',
  path: '/api/ga4/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPProjectIdSettingsRoute =
  ProjectPProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSearchPerformanceRoute =
  ProjectPProjectIdSearchPerformanceRouteImport.update({
    id: '/search-performance',
    path: '/search-performance',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSavedRoute = ProjectPProjectIdSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdRankingsRoute =
  ProjectPProjectIdRankingsRouteImport.update({
    id: '/rankings',
    path: '/rankings',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdOpportunitiesRoute =
  ProjectPProjectIdOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdContextRoute =
  ProjectPProjectIdContextRouteImport.update({
    id: '/context',
    path: '/context',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdAuditRoute = ProjectPProjectIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdAnalyticsRoute =
  ProjectPProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSettingsIndexRoute =
  ProjectPProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdSettingsRoute,
  } as any)
const ProjectPProjectIdReportsIndexRoute =
  ProjectPProjectIdReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdAuditIndexRoute =
  ProjectPProjectIdAuditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdAuditRoute,
  } as any)
const ProjectPProjectIdSettingsIntegrationsRoute =
  ProjectPProjectIdSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ProjectPProjectIdSettingsRoute,
  } as any)
const ProjectPProjectIdSettingsContextRoute =
  ProjectPProjectIdSettingsContextRouteImport.update({
    id: '/context',
    path: '/context',
    getParentRoute: () => ProjectPProjectIdSettingsRoute,
  } as any)
const ProjectPProjectIdReportsTemplatesRoute =
  ProjectPProjectIdReportsTemplatesRouteImport.update({
    id: '/reports/templates',
    path: '/reports/templates',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdReportsReportIdRoute =
  ProjectPProjectIdReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdAuditIssuesResultIdRoute =
  ProjectPProjectIdAuditIssuesResultIdRouteImport.update({
    id: '/issues/$resultId',
    path: '/issues/$resultId',
    getParentRoute: () => ProjectPProjectIdAuditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai': typeof AppAiRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/support': typeof AppSupportRoute
  '/api/health': typeof ApiHealthRoute
  '/r/$reportId': typeof RReportIdRoute
  '/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/settings/': typeof AppSettingsIndexRoute
  '/p/$projectId/analytics': typeof ProjectPProjectIdAnalyticsRoute
  '/p/$projectId/audit': typeof ProjectPProjectIdAuditRouteWithChildren
  '/p/$projectId/context': typeof ProjectPProjectIdContextRoute
  '/p/$projectId/opportunities': typeof ProjectPProjectIdOpportunitiesRoute
  '/p/$projectId/rankings': typeof ProjectPProjectIdRankingsRoute
  '/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/p/$projectId/search-performance': typeof ProjectPProjectIdSearchPerformanceRoute
  '/p/$projectId/settings': typeof ProjectPProjectIdSettingsRouteWithChildren
  '/api/ga4/oauth/callback': typeof ApiGa4OauthCallbackRoute
  '/api/gsc/oauth/callback': typeof ApiGscOauthCallbackRoute
  '/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/reports/$reportId': typeof ProjectPProjectIdReportsReportIdRoute
  '/p/$projectId/reports/templates': typeof ProjectPProjectIdReportsTemplatesRoute
  '/p/$projectId/settings/context': typeof ProjectPProjectIdSettingsContextRoute
  '/p/$projectId/settings/integrations': typeof ProjectPProjectIdSettingsIntegrationsRoute
  '/p/$projectId/audit/': typeof ProjectPProjectIdAuditIndexRoute
  '/p/$projectId/reports/': typeof ProjectPProjectIdReportsIndexRoute
  '/p/$projectId/settings/': typeof ProjectPProjectIdSettingsIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/ai': typeof AppAiRoute
  '/projects': typeof AppProjectsRoute
  '/support': typeof AppSupportRoute
  '/api/health': typeof ApiHealthRoute
  '/r/$reportId': typeof RReportIdRoute
  '/settings': typeof AppSettingsIndexRoute
  '/p/$projectId/analytics': typeof ProjectPProjectIdAnalyticsRoute
  '/p/$projectId/context': typeof ProjectPProjectIdContextRoute
  '/p/$projectId/opportunities': typeof ProjectPProjectIdOpportunitiesRoute
  '/p/$projectId/rankings': typeof ProjectPProjectIdRankingsRoute
  '/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/p/$projectId/search-performance': typeof ProjectPProjectIdSearchPerformanceRoute
  '/api/ga4/oauth/callback': typeof ApiGa4OauthCallbackRoute
  '/api/gsc/oauth/callback': typeof ApiGscOauthCallbackRoute
  '/p/$projectId': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/reports/$reportId': typeof ProjectPProjectIdReportsReportIdRoute
  '/p/$projectId/reports/templates': typeof ProjectPProjectIdReportsTemplatesRoute
  '/p/$projectId/settings/context': typeof ProjectPProjectIdSettingsContextRoute
  '/p/$projectId/settings/integrations': typeof ProjectPProjectIdSettingsIntegrationsRoute
  '/p/$projectId/audit': typeof ProjectPProjectIdAuditIndexRoute
  '/p/$projectId/reports': typeof ProjectPProjectIdReportsIndexRoute
  '/p/$projectId/settings': typeof ProjectPProjectIdSettingsIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_project': typeof ProjectRouteRouteWithChildren
  '/_app/ai': typeof AppAiRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/support': typeof AppSupportRoute
  '/api/health': typeof ApiHealthRoute
  '/r/$reportId': typeof RReportIdRoute
  '/_app/': typeof AppIndexRoute
  '/_project/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_project/p/$projectId/analytics': typeof ProjectPProjectIdAnalyticsRoute
  '/_project/p/$projectId/audit': typeof ProjectPProjectIdAuditRouteWithChildren
  '/_project/p/$projectId/context': typeof ProjectPProjectIdContextRoute
  '/_project/p/$projectId/opportunities': typeof ProjectPProjectIdOpportunitiesRoute
  '/_project/p/$projectId/rankings': typeof ProjectPProjectIdRankingsRoute
  '/_project/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/_project/p/$projectId/search-performance': typeof ProjectPProjectIdSearchPerformanceRoute
  '/_project/p/$projectId/settings': typeof ProjectPProjectIdSettingsRouteWithChildren
  '/api/ga4/oauth/callback': typeof ApiGa4OauthCallbackRoute
  '/api/gsc/oauth/callback': typeof ApiGscOauthCallbackRoute
  '/_project/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/_project/p/$projectId/reports/$reportId': typeof ProjectPProjectIdReportsReportIdRoute
  '/_project/p/$projectId/reports/templates': typeof ProjectPProjectIdReportsTemplatesRoute
  '/_project/p/$projectId/settings/context': typeof ProjectPProjectIdSettingsContextRoute
  '/_project/p/$projectId/settings/integrations': typeof ProjectPProjectIdSettingsIntegrationsRoute
  '/_project/p/$projectId/audit/': typeof ProjectPProjectIdAuditIndexRoute
  '/_project/p/$projectId/reports/': typeof ProjectPProjectIdReportsIndexRoute
  '/_project/p/$projectId/settings/': typeof ProjectPProjectIdSettingsIndexRoute
  '/_project/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/projects'
    | '/settings'
    | '/support'
    | '/api/health'
    | '/r/$reportId'
    | '/p/$projectId'
    | '/settings/'
    | '/p/$projectId/analytics'
    | '/p/$projectId/audit'
    | '/p/$projectId/context'
    | '/p/$projectId/opportunities'
    | '/p/$projectId/rankings'
    | '/p/$projectId/saved'
    | '/p/$projectId/search-performance'
    | '/p/$projectId/settings'
    | '/api/ga4/oauth/callback'
    | '/api/gsc/oauth/callback'
    | '/p/$projectId/'
    | '/p/$projectId/reports/$reportId'
    | '/p/$projectId/reports/templates'
    | '/p/$projectId/settings/context'
    | '/p/$projectId/settings/integrations'
    | '/p/$projectId/audit/'
    | '/p/$projectId/reports/'
    | '/p/$projectId/settings/'
    | '/p/$projectId/audit/issues/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/projects'
    | '/support'
    | '/api/health'
    | '/r/$reportId'
    | '/settings'
    | '/p/$projectId/analytics'
    | '/p/$projectId/context'
    | '/p/$projectId/opportunities'
    | '/p/$projectId/rankings'
    | '/p/$projectId/saved'
    | '/p/$projectId/search-performance'
    | '/api/ga4/oauth/callback'
    | '/api/gsc/oauth/callback'
    | '/p/$projectId'
    | '/p/$projectId/reports/$reportId'
    | '/p/$projectId/reports/templates'
    | '/p/$projectId/settings/context'
    | '/p/$projectId/settings/integrations'
    | '/p/$projectId/audit'
    | '/p/$projectId/reports'
    | '/p/$projectId/settings'
    | '/p/$projectId/audit/issues/$resultId'
  id:
    | '__root__'
    | '/_app'
    | '/_project'
    | '/_app/ai'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/support'
    | '/api/health'
    | '/r/$reportId'
    | '/_app/'
    | '/_project/p/$projectId'
    | '/_app/settings/'
    | '/_project/p/$projectId/analytics'
    | '/_project/p/$projectId/audit'
    | '/_project/p/$projectId/context'
    | '/_project/p/$projectId/opportunities'
    | '/_project/p/$projectId/rankings'
    | '/_project/p/$projectId/saved'
    | '/_project/p/$projectId/search-performance'
    | '/_project/p/$projectId/settings'
    | '/api/ga4/oauth/callback'
    | '/api/gsc/oauth/callback'
    | '/_project/p/$projectId/'
    | '/_project/p/$projectId/reports/$reportId'
    | '/_project/p/$projectId/reports/templates'
    | '/_project/p/$projectId/settings/context'
    | '/_project/p/$projectId/settings/integrations'
    | '/_project/p/$projectId/audit/'
    | '/_project/p/$projectId/reports/'
    | '/_project/p/$projectId/settings/'
    | '/_project/p/$projectId/audit/issues/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  RReportIdRoute: typeof RReportIdRoute
  ApiGa4OauthCallbackRoute: typeof ApiGa4OauthCallbackRoute
  ApiGscOauthCallbackRoute: typeof ApiGscOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/r/$reportId': {
      id: '/r/$reportId'
      path: '/r/$reportId'
      fullPath: '/r/$reportId'
      preLoaderRoute: typeof RReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_project/p/$projectId': {
      id: '/_project/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof ProjectPProjectIdRouteRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/p/$projectId/': {
      id: '/_project/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof ProjectPProjectIdIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/api/gsc/oauth/callback': {
      id: '/api/gsc/oauth/callback'
      path: '/api/gsc/oauth/callback'
      fullPath: '/api/gsc/oauth/callback'
      preLoaderRoute: typeof ApiGscOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ga4/oauth/callback': {
      id: '/api/ga4/oauth/callback'
      path: '/api/ga4/oauth/callback'
      fullPath: '/api/ga4/oauth/callback'
      preLoaderRoute: typeof ApiGa4OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project/p/$projectId/settings': {
      id: '/_project/p/$projectId/settings'
      path: '/settings'
      fullPath: '/p/$projectId/settings'
      preLoaderRoute: typeof ProjectPProjectIdSettingsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/search-performance': {
      id: '/_project/p/$projectId/search-performance'
      path: '/search-performance'
      fullPath: '/p/$projectId/search-performance'
      preLoaderRoute: typeof ProjectPProjectIdSearchPerformanceRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/saved': {
      id: '/_project/p/$projectId/saved'
      path: '/saved'
      fullPath: '/p/$projectId/saved'
      preLoaderRoute: typeof ProjectPProjectIdSavedRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/rankings': {
      id: '/_project/p/$projectId/rankings'
      path: '/rankings'
      fullPath: '/p/$projectId/rankings'
      preLoaderRoute: typeof ProjectPProjectIdRankingsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/opportunities': {
      id: '/_project/p/$projectId/opportunities'
      path: '/opportunities'
      fullPath: '/p/$projectId/opportunities'
      preLoaderRoute: typeof ProjectPProjectIdOpportunitiesRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/context': {
      id: '/_project/p/$projectId/context'
      path: '/context'
      fullPath: '/p/$projectId/context'
      preLoaderRoute: typeof ProjectPProjectIdContextRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/audit': {
      id: '/_project/p/$projectId/audit'
      path: '/audit'
      fullPath: '/p/$projectId/audit'
      preLoaderRoute: typeof ProjectPProjectIdAuditRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/analytics': {
      id: '/_project/p/$projectId/analytics'
      path: '/analytics'
      fullPath: '/p/$projectId/analytics'
      preLoaderRoute: typeof ProjectPProjectIdAnalyticsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/settings/': {
      id: '/_project/p/$projectId/settings/'
      path: '/'
      fullPath: '/p/$projectId/settings/'
      preLoaderRoute: typeof ProjectPProjectIdSettingsIndexRouteImport
      parentRoute: typeof ProjectPProjectIdSettingsRoute
    }
    '/_project/p/$projectId/reports/': {
      id: '/_project/p/$projectId/reports/'
      path: '/reports'
      fullPath: '/p/$projectId/reports/'
      preLoaderRoute: typeof ProjectPProjectIdReportsIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/audit/': {
      id: '/_project/p/$projectId/audit/'
      path: '/'
      fullPath: '/p/$projectId/audit/'
      preLoaderRoute: typeof ProjectPProjectIdAuditIndexRouteImport
      parentRoute: typeof ProjectPProjectIdAuditRoute
    }
    '/_project/p/$projectId/settings/integrations': {
      id: '/_project/p/$projectId/settings/integrations'
      path: '/integrations'
      fullPath: '/p/$projectId/settings/integrations'
      preLoaderRoute: typeof ProjectPProjectIdSettingsIntegrationsRouteImport
      parentRoute: typeof ProjectPProjectIdSettingsRoute
    }
    '/_project/p/$projectId/settings/context': {
      id: '/_project/p/$projectId/settings/context'
      path: '/context'
      fullPath: '/p/$projectId/settings/context'
      preLoaderRoute: typeof ProjectPProjectIdSettingsContextRouteImport
      parentRoute: typeof ProjectPProjectIdSettingsRoute
    }
    '/_project/p/$projectId/reports/templates': {
      id: '/_project/p/$projectId/reports/templates'
      path: '/reports/templates'
      fullPath: '/p/$projectId/reports/templates'
      preLoaderRoute: typeof ProjectPProjectIdReportsTemplatesRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/reports/$reportId': {
      id: '/_project/p/$projectId/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/p/$projectId/reports/$reportId'
      preLoaderRoute: typeof ProjectPProjectIdReportsReportIdRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/audit/issues/$resultId': {
      id: '/_project/p/$projectId/audit/issues/$resultId'
      path: '/issues/$resultId'
      fullPath: '/p/$projectId/audit/issues/$resultId'
      preLoaderRoute: typeof ProjectPProjectIdAuditIssuesResultIdRouteImport
      parentRoute: typeof ProjectPProjectIdAuditRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ProjectPProjectIdAuditRouteChildren {
  ProjectPProjectIdAuditIndexRoute: typeof ProjectPProjectIdAuditIndexRoute
  ProjectPProjectIdAuditIssuesResultIdRoute: typeof ProjectPProjectIdAuditIssuesResultIdRoute
}

const ProjectPProjectIdAuditRouteChildren: ProjectPProjectIdAuditRouteChildren =
  {
    ProjectPProjectIdAuditIndexRoute: ProjectPProjectIdAuditIndexRoute,
    ProjectPProjectIdAuditIssuesResultIdRoute:
      ProjectPProjectIdAuditIssuesResultIdRoute,
  }

const ProjectPProjectIdAuditRouteWithChildren =
  ProjectPProjectIdAuditRoute._addFileChildren(
    ProjectPProjectIdAuditRouteChildren,
  )

interface ProjectPProjectIdSettingsRouteChildren {
  ProjectPProjectIdSettingsContextRoute: typeof ProjectPProjectIdSettingsContextRoute
  ProjectPProjectIdSettingsIntegrationsRoute: typeof ProjectPProjectIdSettingsIntegrationsRoute
  ProjectPProjectIdSettingsIndexRoute: typeof ProjectPProjectIdSettingsIndexRoute
}

const ProjectPProjectIdSettingsRouteChildren: ProjectPProjectIdSettingsRouteChildren =
  {
    ProjectPProjectIdSettingsContextRoute:
      ProjectPProjectIdSettingsContextRoute,
    ProjectPProjectIdSettingsIntegrationsRoute:
      ProjectPProjectIdSettingsIntegrationsRoute,
    ProjectPProjectIdSettingsIndexRoute: ProjectPProjectIdSettingsIndexRoute,
  }

const ProjectPProjectIdSettingsRouteWithChildren =
  ProjectPProjectIdSettingsRoute._addFileChildren(
    ProjectPProjectIdSettingsRouteChildren,
  )

interface ProjectPProjectIdRouteRouteChildren {
  ProjectPProjectIdAnalyticsRoute: typeof ProjectPProjectIdAnalyticsRoute
  ProjectPProjectIdAuditRoute: typeof ProjectPProjectIdAuditRouteWithChildren
  ProjectPProjectIdContextRoute: typeof ProjectPProjectIdContextRoute
  ProjectPProjectIdOpportunitiesRoute: typeof ProjectPProjectIdOpportunitiesRoute
  ProjectPProjectIdRankingsRoute: typeof ProjectPProjectIdRankingsRoute
  ProjectPProjectIdSavedRoute: typeof ProjectPProjectIdSavedRoute
  ProjectPProjectIdSearchPerformanceRoute: typeof ProjectPProjectIdSearchPerformanceRoute
  ProjectPProjectIdSettingsRoute: typeof ProjectPProjectIdSettingsRouteWithChildren
  ProjectPProjectIdIndexRoute: typeof ProjectPProjectIdIndexRoute
  ProjectPProjectIdReportsReportIdRoute: typeof ProjectPProjectIdReportsReportIdRoute
  ProjectPProjectIdReportsTemplatesRoute: typeof ProjectPProjectIdReportsTemplatesRoute
  ProjectPProjectIdReportsIndexRoute: typeof ProjectPProjectIdReportsIndexRoute
}

const ProjectPProjectIdRouteRouteChildren: ProjectPProjectIdRouteRouteChildren =
  {
    ProjectPProjectIdAnalyticsRoute: ProjectPProjectIdAnalyticsRoute,
    ProjectPProjectIdAuditRoute: ProjectPProjectIdAuditRouteWithChildren,
    ProjectPProjectIdContextRoute: ProjectPProjectIdContextRoute,
    ProjectPProjectIdOpportunitiesRoute: ProjectPProjectIdOpportunitiesRoute,
    ProjectPProjectIdRankingsRoute: ProjectPProjectIdRankingsRoute,
    ProjectPProjectIdSavedRoute: ProjectPProjectIdSavedRoute,
    ProjectPProjectIdSearchPerformanceRoute:
      ProjectPProjectIdSearchPerformanceRoute,
    ProjectPProjectIdSettingsRoute: ProjectPProjectIdSettingsRouteWithChildren,
    ProjectPProjectIdIndexRoute: ProjectPProjectIdIndexRoute,
    ProjectPProjectIdReportsReportIdRoute:
      ProjectPProjectIdReportsReportIdRoute,
    ProjectPProjectIdReportsTemplatesRoute:
      ProjectPProjectIdReportsTemplatesRoute,
    ProjectPProjectIdReportsIndexRoute: ProjectPProjectIdReportsIndexRoute,
  }

const ProjectPProjectIdRouteRouteWithChildren =
  ProjectPProjectIdRouteRoute._addFileChildren(
    ProjectPProjectIdRouteRouteChildren,
  )

interface ProjectRouteRouteChildren {
  ProjectPProjectIdRouteRoute: typeof ProjectPProjectIdRouteRouteWithChildren
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectPProjectIdRouteRoute: ProjectPProjectIdRouteRouteWithChildren,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  RReportIdRoute: RReportIdRoute,
  ApiGa4OauthCallbackRoute: ApiGa4OauthCallbackRoute,
  ApiGscOauthCallbackRoute: ApiGscOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
